name: Check Connectivity

on:
    schedule:
      - cron: '*/1 * * * *'
    push:

  jobs:
    check:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v2
        
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'
        - name: Install Ansible
          run: |
            sudo apt update
            sudo apt upgrade
            sudo apt -y install software-properties-common
            sudo apt-add-repository ppa:ansible/ansible
            sudo apt install -y ansible
        - name: Run Ansible Playbook
          run: ansible-playbook check_status.yml
