name: Install Ansible
on: push
jobs:
  install-ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt -y install software-properties-common
          sudo apt-add-repository ppa:ansible/ansible
          sudo apt install -y ansible

